apiVersion: apps/v1
kind: Deployment
metadata:
  name: _APP_NAME_
  labels:
    app: _APP_NAME_
spec:
  replicas: _REPLICAS_
  selector:
    matchLabels:
      app: _APP_NAME_
  template:
    metadata:
      labels:
        app: _APP_NAME_
    spec:
      containers:
        - name: _APP_NAME_
          image: _REGISTRY_/_PROJECT_ID_/_APP_NAME_:_VERSION_
          imagePullPolicy: Always
          ports:
            - containerPort: _PORT_
          readinessProbe:
            httpGet:
              port: 80
              path: /
              httpHeaders:
                - name: test
                  value: _AMAZON_USER_SECRET_KEY_
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: _APP_NAME_-service
  labels:
    app: _APP_NAME_
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: _PORT_
      name: http
  selector:
    app: _APP_NAME_
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "test-ingress"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.com/health-checks: "true"
  labels:
    app: test-app
spec:
  rules:
    - host: test.phuoc.pro
      http:
        paths:
          - backend:
              serviceName: _APP_NAME_-service
              servicePort: 80