
replicaCount: 1

service:
  type: NodePort
  port: 80
  containerPort: 80

image:
  repository: gcr.io/precise/https-test
  tag: v1.0.2
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.com/health-checks: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

livenessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  initialDelaySeconds: 50
  periodSeconds: 30
  timeoutSeconds: 30
readinessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  initialDelaySeconds: 50
  periodSeconds: 30
  timeoutSeconds: 30

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 50Mi

